### ISSUE TITLE
NullPointerException przy włączonej kolejności FIL i używaniu "Omiń aktualnego..."

### ISSUE THREAD

**Issue by SP8EBC** [SP8EBC/MKS_JG#1]
Po załadowaniu pliku memorial2018_wpg_l15.xml i przełączeniu konkurencji na "Młodziczka" wskakuje na drugi ślizg treningowy (dobrze). Po użyciu przycisku "Omiń aktualnego i przejdź do następnego" wyskakuje 

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at pl.jeleniagora.mks.start.order.FilOrder.nextStartNumber(FilOrder.java:51)
	at pl.jeleniagora.mks.events.UpdateCurrentAndNextLuger.findFirstWithoutTime(UpdateCurrentAndNextLuger.java:149)
	at pl.jeleniagora.mks.events.UpdateCurrentAndNextLuger.moveForwardNormally(UpdateCurrentAndNextLuger.java:415)
	at pl.jeleniagora.mks.gui.CompManagerNextLugerBtnActionListener.actionPerformed(CompManagerNextLugerBtnActionListener.java:43)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

problem jest powtarzalny

**Comment by SP8EBC** [comment]
W konkurencji młodzczki numer 13 jest jako aktualnie na torze a numer 21 jako następny. Tylko numery 13 i 21 nie mają czasu ślizgu, jest też numer 30 DNS

W metodzie moveForwardNormally() jest miejsce w liniii 387
`		
                /*
		 * Sprawdzanie czy nie doszło się do końca aktualnej konkurencji, tj czy następny na torze nie 
                 jest 
		 * jednocześnie ostatnim. Srawdzenie via nasatępny takie jest wymagane ze względu na 
                 funkcjonalność "ustaw aktualnie
		 * zaznaczonego jako nastepnego (...)
		 */
		if (!order.checkIfLastInRun(next, currentCompetition, currentRun))
		{
			/*
			 * Numery startowe są liczone od jedynki, dlatego jeżeli następny będzie miał nr 9 a jest 
                        10 wszystkich
			 * to jeszcze można przypisać kogoś za nim
			 */
			rte_st.actuallyOnTrack = rte_st.currentCompetition.invertedStartList.get((short)(nextStartNumber));
			
			/*
			 * Sprawdzanie czy kolejny nr startowy za obecnym "następnie' ma już jakiś czas przejazdu czy nie. Może się bowiem zdarzyć, 
			 * że po kilkukrotnym użyciu funkcji "Ustaw zaznaczonego w tabeli (...)" kolejność całkiem się przemiesza i np. co drugi już pojechał
			 * a co drugi jeszcze nie.
			 */
`
gdzie ten If ma przy takim ustawieniu zawodników zwrócić true bo nr 21 jest ostatni

**Comment by SP8EBC** [comment]
Poprawiono!
