### ISSUE TITLE
NullPointerException bez DNS/DSQ i z kolejnością FIL po użyciu przycisku "Omiń Aktualnego.."

### ISSUE THREAD

**Issue by SP8EBC** [SP8EBC/MKS_JG#2]
memorial2018_wpg_l35.xml Po przełączeniu się na "Młodzik" wskakuje drugi Ślizg punktowny. Nie ma nikogo z DNF ani DSQ ani DNS. Kilkukrotne użycie "Omiń Aaktualnego..." Powoduje wyciepanie się wyjątku 

Changing current competition to: Młodzik
markConcreteRun - rts 5 - cts 8 - startnum10
runtimeFromChrono = false
Clicked run: Ślizg punktowny numer 2
runtimeFromChrono = false
markConcreteRun - rts 5 - cts 8 - startnum10
markConcreteRun - rts 1 - cts 8 - startnum132
Clicked run: Ślizg punktowny numer 2
runtimeFromChrono = false
markConcreteRun - rts 4 - cts 8 - startnum27
Clicked run: Ślizg punktowny numer 2
runtimeFromChrono = false
markConcreteRun - rts 2 - cts 8 - startnum134
Clicked run: Ślizg punktowny numer 2
runtimeFromChrono = false
Candidate to nextOnTrack has non zero runtime
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at pl.jeleniagora.mks.start.order.FilOrder.nextStartNumber(FilOrder.java:51)
	at pl.jeleniagora.mks.events.UpdateCurrentAndNextLuger.findFirstWithoutTime(UpdateCurrentAndNextLuger.java:149)
	at pl.jeleniagora.mks.events.UpdateCurrentAndNextLuger.moveForwardNormally(UpdateCurrentAndNextLuger.java:415)
	at pl.jeleniagora.mks.gui.CompManagerNextLugerBtnActionListener.actionPerformed(CompManagerNextLugerBtnActionListener.java:43)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by SP8EBC** [comment]
Przetestowane. Poprawka działa poprawnie https://github.com/SP8EBC/MKS_JG/commit/bd182baea05225ecf54aad2f204194d5ddebcf06
